$(document).ready(function() {
	
//	$("body").append('<div class="color_panel"><a href="javascript:void(0)" class="cpl_toggle cpl_show"></a><div class="ttl_block">Choose your style</div><div class="categs"><ul><li><a href="javascript:void(0)" class="panel_accordion">Layout</a><ul class="layout_categ"><li><a href="javascript:void(0)" rel="layout_streched">Stretched</a></li><li><a href="javascript:void(0)" rel="layout_boxed">Boxed</a></li><li><a href="javascript:void(0)" rel="layout_background">Background image</a></li></ul></li><li><a href="javascript:void(0)" class="panel_accordion">Color</a><ul class="color_categ"><li class="color1"><a href="javascript:void(0)" rel="color_green"></a></li><li class="color2"><a href="javascript:void(0)" rel="color_turquoise"></a></li><li class="color3"><a href="javascript:void(0)" rel="color_celestial"></a></li><li class="color4"><a href="javascript:void(0)" rel="color_ceruleum"></a></li><li class="color5"><a href="javascript:void(0)" rel="color_violet"></a></li><li class="color6"><a href="javascript:void(0)" rel="color_purpure"></a></li><li class="color7"><a href="javascript:void(0)" rel="color_carmine"></a></li><li class="color8"><a href="javascript:void(0)" rel="color_pink"></a></li><li class="color9"><a href="javascript:void(0)" rel="color_red"></a></li><li class="color10"><a href="javascript:void(0)" rel="color_cadmium"></a></li><li class="color11"><a href="javascript:void(0)" rel="color_orange"></a></li><li class="color12"><a href="javascript:void(0)" rel="color_yellow"></a></li></ul></li><li><a href="javascript:void(0)" class="panel_accordion">Skin</a><ul class="theme_categ"><li><a href="javascript:void(0)" rel="skin_light">Light</a></li><li><a href="javascript:void(0)" rel="skin_dark">Dark</a></li></ul></li><li><a href="javascript:void(0)" class="panel_accordion">Background</a><ul class="bg_categ"><li><a href="javascript:void(0)" rel="lines1">Lines 01</a></li><li><a href="javascript:void(0)" rel="lines2">Lines 02</a></li><li><a href="javascript:void(0)" rel="lines3">Lines 03</a></li><li><a href="javascript:void(0)" rel="lines4">Lines 04</a></li><li><a href="javascript:void(0)" rel="grid1">Grid 01</a></li><li><a href="javascript:void(0)" rel="grid2">Grid 02</a></li><li><a href="javascript:void(0)" rel="dots">Dots</a></li></ul></li></ul></div></div>');
    $("body").append('<div class="style_panel"><a class="cpl_toggle icon cpl_show">s</a><div class="ttl_block">settings</div><div class="categs"><ul><li><a class="panel_accordion">Layout</a><ul class="layout_categ"><li><a rel="layout_boxed">Boxed</a></li><li><a rel="layout_stretched">Stretched</a></li><li><a rel="layout_background">Background image</a></li></ul></li><li><a class="panel_accordion">Color</a><ul class="color_categ"><li class="color1"><a href="javascript:void(0)" rel="color_green"></a></li><li class="color2"><a href="javascript:void(0)" rel="color_turquoise"></a></li><li class="color3"><a href="javascript:void(0)" rel="color_celestial"></a></li><li class="color4"><a href="javascript:void(0)" rel="color_ceruleum"></a></li><li class="color5"><a href="javascript:void(0)" rel="color_violet"></a></li><li class="color6"><a href="javascript:void(0)" rel="color_purpure"></a></li><li class="color7"><a href="javascript:void(0)" rel="color_carmine"></a></li><li class="color8"><a href="javascript:void(0)" rel="color_pink"></a></li><li class="color9"><a href="javascript:void(0)" rel="color_red"></a></li><li class="color10"><a href="javascript:void(0)" rel="color_cadmium"></a></li><li class="color11"><a href="javascript:void(0)" rel="color_orange"></a></li><li class="color12"><a href="javascript:void(0)" rel="color_yellow"></a></li></ul></li><li><a class="panel_accordion">background pattern</a><ul class="bg_categ"><li><a rel="dott">Dots</a></li><li><a rel="grid2">Grig 02</a></li><li><a rel="grid1">Grig 01</a></li><li><a rel="lines3">Line 03</a></li><li><a rel="lines2">Line 02</a></li><li><a rel="lines1">Line 01</a></li></ul></li></ul></div></div>')
	
	if ($.cookie("cookie_layout")) {
		$('#css_layout').attr('href', 'css/layout/' + $.cookie("cookie_layout") + '.css');
	} else {
		$('#css_layout').attr('href', 'css/layout/layout_boxed.css');
	}
	if ($.cookie("cookie_color")) {
		$('#css_color').attr('href', 'css/colors/' + $.cookie("cookie_color") + '.css');
	} else {
		$('#css_color').attr('href', 'css/colors/color_red.css');
	}
	if ($.cookie("cookie_pattern")) {
		$('#css_pattern').attr('href', 'css/patterns/' + $.cookie("cookie_pattern") + '.css');
	} else {
		$('#css_pattern').attr('href', 'css/patterns/lines1.css');
	}
});
